# Generated by Django 4.1.2 on 2023-02-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ambulance',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='hospital',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
