# Generated by Django 4.1.2 on 2023-02-18 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0003_ambulance_post_hospital_post_user_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='post',
            new_name='usertype',
        ),
    ]
