# Generated by Django 4.1.2 on 2023-02-19 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0004_rename_post_user_usertype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ambulance',
            old_name='post',
            new_name='usertype',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='post',
            new_name='usertype',
        ),
    ]
