# Generated by Django 4.1.2 on 2023-03-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0006_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='hos_patient',
            fields=[
                ('fname', models.CharField(max_length=30)),
                ('midname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('dateOfRequest', models.CharField(max_length=8)),
                ('timeOfRequest', models.CharField(max_length=8)),
                ('am_pm', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=20, primary_key=True, serialize=False)),
                ('phNo', models.CharField(max_length=10)),
                ('pickupStreet', models.CharField(max_length=8)),
                ('pickupCity', models.CharField(max_length=20)),
                ('pickupState', models.CharField(max_length=30)),
                ('pickupZip', models.CharField(max_length=30)),
                ('dob', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=15)),
                ('relation', models.CharField(max_length=30)),
                ('medical_con', models.CharField(max_length=30)),
                ('resonForAmb', models.CharField(max_length=30)),
            ],
        ),
    ]
