# Generated by Django 4.1.2 on 2023-03-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0007_hos_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hos_patient',
            name='pickupStreet',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pickupStreet',
            field=models.CharField(max_length=20),
        ),
    ]
