# Generated by Django 4.1.2 on 2023-03-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0008_alter_hos_patient_pickupstreet_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hos_patient',
            old_name='pickupCity',
            new_name='City',
        ),
        migrations.RenameField(
            model_name='hos_patient',
            old_name='pickupState',
            new_name='State',
        ),
        migrations.RenameField(
            model_name='hos_patient',
            old_name='pickupStreet',
            new_name='Street',
        ),
        migrations.RenameField(
            model_name='hos_patient',
            old_name='pickupZip',
            new_name='Zip',
        ),
        migrations.RenameField(
            model_name='hos_patient',
            old_name='resonForAmb',
            new_name='resonForHos',
        ),
        migrations.AlterField(
            model_name='hos_patient',
            name='midname',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='midname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
