# Generated by Django 4.1.2 on 2023-03-11 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0011_av_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='av_hospital',
            name='phNo',
            field=models.CharField(max_length=12),
        ),
    ]
