# Generated by Django 4.1.2 on 2023-03-23 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0012_alter_av_hospital_phno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambulance',
            name='usertype',
        ),
    ]
