# Generated by Django 4.1.2 on 2023-03-23 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0014_ambulance_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='hos_patient',
            name='Ugmail',
            field=models.ForeignKey(default='ritz21ch@gmail.com', on_delete=django.db.models.deletion.CASCADE, to='BookingApp.user'),
        ),
    ]
