# Generated by Django 4.1.2 on 2023-03-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0015_hos_patient_ugmail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hos_patient',
            name='dateOfRequest',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='hos_patient',
            name='midname',
            field=models.CharField(max_length=30),
        ),
    ]
