# Generated by Django 4.1.2 on 2023-03-23 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0016_alter_hos_patient_dateofrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hos_patient',
            name='Av_gmail',
            field=models.ForeignKey(default='medisquarehospital@gmail.com', on_delete=django.db.models.deletion.CASCADE, to='BookingApp.av_hospital'),
        ),
        migrations.AlterField(
            model_name='av_hospital',
            name='City',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='av_hospital',
            name='State',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='av_hospital',
            name='Street',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hos_patient',
            name='City',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hos_patient',
            name='State',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hos_patient',
            name='Street',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='hos_patient',
            name='midname',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='patient',
            name='descity',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='desstate',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='desstreet',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='midname',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pickupCity',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pickupState',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pickupStreet',
            field=models.CharField(max_length=50),
        ),
    ]
