# Generated by Django 4.1.2 on 2023-03-23 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0017_hos_patient_av_gmail_alter_av_hospital_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hos_patient',
            old_name='Av_gmail',
            new_name='AvHospital_gmail',
        ),
        migrations.RenameField(
            model_name='hos_patient',
            old_name='Ugmail',
            new_name='User_gmail',
        ),
        migrations.AddField(
            model_name='av_hospital',
            name='Hospital_gmail',
            field=models.ForeignKey(default='medisquarehospital@gmail.com', on_delete=django.db.models.deletion.CASCADE, to='BookingApp.hospital'),
        ),
    ]
