# Generated by Django 4.1.2 on 2023-03-23 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0018_rename_av_gmail_hos_patient_avhospital_gmail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='av_hospital',
            old_name='Hospital_gmail',
            new_name='Hospital_email',
        ),
    ]
