# Generated by Django 4.1.2 on 2023-03-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0019_rename_hospital_gmail_av_hospital_hospital_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulance',
            name='email',
            field=models.EmailField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
