# Generated by Django 4.1.2 on 2023-03-23 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0020_alter_ambulance_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulance',
            name='usertype',
            field=models.CharField(default='ambulance', max_length=30),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='usertype',
            field=models.CharField(default='hospital', max_length=30),
        ),
        migrations.CreateModel(
            name='av_ambulance',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=30, primary_key=True, serialize=False)),
                ('phNo', models.CharField(max_length=12)),
                ('Street', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('Zip', models.CharField(max_length=30)),
                ('NoOfAmb', models.IntegerField()),
                ('Ambulance_email', models.ForeignKey(default='medisquarehospital@gmail.com', on_delete=django.db.models.deletion.CASCADE, to='BookingApp.ambulance')),
            ],
        ),
    ]
