# Generated by Django 4.1.2 on 2023-03-23 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0022_alter_av_ambulance_noofamb'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Amb_gmail',
            field=models.ForeignKey(default='medisquarehospital@gmail.com', on_delete=django.db.models.deletion.CASCADE, to='BookingApp.ambulance'),
        ),
        migrations.AddField(
            model_name='patient',
            name='AvAmb_gmail',
            field=models.ForeignKey(default='medisquarehospital@gmail.com', on_delete=django.db.models.deletion.CASCADE, to='BookingApp.av_ambulance'),
        ),
    ]
