# Generated by Django 4.1.2 on 2023-04-09 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0023_patient_amb_gmail_patient_avamb_gmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='User_gmail',
            field=models.ForeignKey(default='ritz21ch@gmail.com', on_delete=django.db.models.deletion.CASCADE, to='BookingApp.user'),
        ),
    ]
