# Generated by Django 4.1.2 on 2023-04-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0025_alter_patient_amb_gmail_alter_patient_avamb_gmail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hos_patient',
            name='hospital',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
