# Generated by Django 4.1.2 on 2023-04-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0026_hos_patient_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hos_patient',
            name='midname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
