# Generated by Django 4.1.2 on 2023-04-14 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0027_alter_hos_patient_midname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hos_patient',
            name='AvHospital_gmail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingApp.av_hospital'),
        ),
        migrations.AlterField(
            model_name='hos_patient',
            name='User_gmail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookingApp.user'),
        ),
    ]
