# Generated by Django 4.1.2 on 2023-04-16 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0028_alter_hos_patient_avhospital_gmail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hos_patient',
            name='midname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='hos_patient',
            name='phNo',
            field=models.IntegerField(max_length=10),
        ),
    ]
