# Generated by Django 4.1.2 on 2023-05-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0030_emergency'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
